name: Build and test

on: [push, pull_request]

jobs:
  ghc-test:
    name: Build wrappers with GHC
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Build wrap_parity.hs
      run: nix-shell -p ghc --run "ghc -O2 site/wrap_parity.hs -o wrap_parity"
    - name: Build wrap_patty.hs
      run: nix-shell -p ghc --run "ghc -O2 site/wrap_patty.hs -o wrap_patty"
    - name: Build wrap_marginally.hs
      run: "gcc -c site/stub.c && nix-shell -p \"haskellPackages.ghcWithPackages (h: [ h.raw-strings-qq ])\" --run \"ghc -O2 site/wrap_marginally.hs stub.o -o wrap_marginally\""
    - name: Build wrap_crossly.hs
      run: "gcc -c site/stub.c && nix-shell -p \"haskellPackages.ghcWithPackages (h: [ h.raw-strings-qq ])\" --run \"ghc -O2 site/wrap_crossly.hs stub.o -o wrap_crossly\""
  build-test:
    name: Build and test with mescc-tools-seed
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Build blynn-compiler with mescc-tools-seed
      run: nix-build -A blynn-compiler
      timeout-minutes: 20
    - name: Check hash of raw
      run: echo "f803e4ca8cf281ec971f76a4920767242aa8427850ffbef85f69c4d01f5f3cdd result/share/raw" | sha256sum -c
    - run: cp result/bin/vm vm && cp result/share/raw raw && cp result/bin/precisely precisely
    - run: ./precisely < test/hello.hs > hello.c && gcc -O2 -o hello hello.c && ./hello > hello.txt
    - name: Check hash of hello world test
      run: echo "4dca0fd5f424a31b03ab807cbae77eb32bf2d089eed1cee154b3afed458de0dc  hello.txt" | sha256sum -c
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build result
        path: |
          raw
          vm
          precisely
